### ISSUE TITLE
be careful with CellListMap v0.7.1

### ISSUE THREAD

**Issue by lmiq** [epaillas/contrast#1]
https://github.com/epaillas/contrast/blob/9f54e685733fdaf058179ba0bc68e69386cc9a35/contrast/box/pairwise_velocities/fastmodules/pairwise_velocities.jl#L107

Here, in version `v0.7.1` of CellListMap, you should use:

```
function reduce_hist(hist, hist_threaded)
    hist = hist_threaded[1]
    for i in 2:length(hist_threaded)  # <<<<<< changed
        hist[1] .+= hist_threaded[i][1]
        hist[2] .+= hist_threaded[i][2]
    end
    return hist
end
```

because the number of threads used in practice may not be the same as the number of threads available ([this section ](https://m3g.github.io/CellListMap.jl/stable/parallelization/#Parallelization-splitting-and-reduction)explains with details the new behavior).

(the user base is still small enough so I can check the github repos using the package to warn the users of this change)

**Comment by epaillas** [comment]
Thanks for the heads up and for taking the time to check this. I have updated the code to take care of this issue now.
